var commandMessage = {
    Sys_Info: 'systeminfo',
    Download_Start: 'downloadStart',
    Download_End: 'downloadEnd',
    Player_Register: 'playerRegister',
    Win_ScreenShot: 'winScreenShot',
    Socket_Start: 'socketStart',
    Socket_Connected: 'socketConnected',
    Send_Signal: 'sendSignal',
    Receive_Signal: 'receiveSignal',
    Check_Publishment: 'checkPublishment',
    Button_Clicked: 'buttonClicked',
    Player_Restart: 'restart',
    Player_Shutdown: 'shutdown',
    Check_Upgrade: 'checkUpgrade',
    StartPublishment: 'startPublishment',
    PlayingLog: 'playingLog',
    PlayerDeleted : 'playerDeleted',
    PublishmentDelete: 'publishmentDelete',
    TriggerAction: 'triggerAction',
    AppRestart: 'appRestart',
    WinScreenShotRequest: 'winScreenShotRequest',
    HealthCheck: 'healthCheck',
    InitPlayer: 'initPlayer',
    PlayerReady: 'playerReady',
    ShowUpgradeStatus: 'showUpgradeStatus',
    OpenFFMpeg: 'openFFMpeg',
    OpenWebPage: 'openWebPage',
    CloseWebPage: 'closeWebPage',
    CurrencyData: 'currencyData',
    WorkerLoging: 'workerLoging',
    ScreenLoging: 'screenLoging',
    ConsoleLogging: "consoleLogging",
    PlayerSettingsHere: "playerSettingsHere",
    Get_Publishment: "getPublishment",
    Update_Publisment_Date: "updatePublishmentDate",
    GetWeatherForecast :"getWeatherForecast",
    GetCurrencies :"getCurrencyValue",
    GetNewsData:"getNewsData"

};
